pod "LAAppVersionCheckerWithParse", :path => "../LAAppVersionCheckerWithParse.podspec"
inhibit_all_warnings!

podspec :path => "../LAAppVersionCheckerWithParse.podspec"

target :ExampleLAAppVersionCheckerWithParseTests do
  pod "LAAppVersionCheckerWithParse"
end
